In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [4]:
df = pd.read_csv('ClassifiedData.csv',index_col=0)

In [5]:
df

WTT       PTI       EQW       SBI       LQE       QWG       FDJ  \
0    0.913917  1.162073  0.567946  0.755464  0.780862  0.352608  0.759697   
1    0.635632  1.003722  0.535342  0.825645  0.924109  0.648450  0.675334   
2    0.721360  1.201493  0.921990  0.855595  1.526629  0.720781  1.626351   
3    1.234204  1.386726  0.653046  0.825624  1.142504  0.875128  1.409708   
4    1.279491  0.949750  0.627280  0.668976  1.232537  0.703727  1.115596   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.010953  1.034006  0.853116  0.622460  1.036610  0.586240  0.746811   
996  0.575529  0.955786  0.941835  0.792882  1.414277  1.269540  1.055928   
997  1.135470  0.982462  0.781905  0.916738  0.901031  0.884738  0.386802   
998  1.084894  0.861769  0.407158  0.665696  1.608612  0.943859  0.855806   
999  0.837460  0.961184  0.417006  0.799784  0.934399  0.424762  0.778234   

          PJF       HQE       NXJ  TARGET CLASS  
0    0.643798  0.879422  1.231409             1  
1    1.013546  0.621552  1.492702             0  
2    1.154483  0.957877  1.285597             0  
3    1.380003  1.522692  1.153093             1  
4    0.646691  1.463812  1.419167             1  
..        ...       ...       ...           ...  
995  0.319752  1.117340  1.348517             1  
996  0.713193  0.958684  1.663489             0  
997  0.389584  0.919191  1.385504             1  
998  1.061338  1.277456  1.188063             1  
999  0.907962  1.257190  1.364837             1  

[1000 rows x 11 columns]

In [6]:
x = df.iloc[:,0:10].values

In [7]:
x

array([[0.91391733, 1.16207271, 0.56794585, ..., 0.64379756, 0.87942209,
        1.23140944],
       [0.6356319 , 1.00372163, 0.53534235, ..., 1.01354599, 0.62155222,
        1.4927016 ],
       [0.72135981, 1.20149262, 0.92198973, ..., 1.15448315, 0.95787702,
        1.28559679],
       ...,
       [1.13546983, 0.98246233, 0.78190516, ..., 0.38958442, 0.91919143,
        1.385504  ],
       [1.08489449, 0.86176917, 0.40715771, ..., 1.06133794, 1.27745578,
        1.18806277],
       [0.83745954, 0.96118352, 0.41700599, ..., 0.90796187, 1.25718998,
        1.36483726]])

In [8]:
y = df.iloc[:,10].values

In [9]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
x_train.shape

(800, 10)

In [13]:
x_test.shape

(200, 10)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc = StandardScaler()

In [16]:
x_train = sc.fit_transform(x_train)

In [17]:
x_train

array([[-1.16428283,  1.74757324,  0.20844628, ...,  0.22422252,
        -1.36101157, -0.7134665 ],
       [-1.26715908, -1.24691222, -0.48827923, ...,  0.88059531,
        -0.23156562,  1.52430027],
       [ 1.29644917, -1.64257999, -1.2095008 , ...,  0.59441159,
         0.11532181, -0.26911141],
       ...,
       [ 0.30134784, -1.10125582, -0.67573553, ...,  0.76769243,
         0.2287497 ,  0.2241008 ],
       [ 0.10270957,  1.170617  ,  1.89351913, ...,  1.25205654,
        -1.08094347,  0.4909162 ],
       [-1.09616081,  0.28961591,  1.54768245, ...,  1.5072054 ,
        -0.50047161,  0.4868709 ]])

In [18]:
x_test = sc.transform(x_test)

In [19]:
x_test

array([[-0.70761861, -0.26269153, -0.38520858, ..., -0.7889067 ,
         1.04297519, -1.3363473 ],
       [-0.59700716,  0.27510449,  1.18741498, ...,  1.17276938,
        -0.89028655,  1.50932012],
       [-0.3863033 ,  0.23230959, -0.21203786, ...,  1.2814097 ,
         0.33175346,  0.2348103 ],
       ...,
       [-0.59226834, -1.25232653, -1.25637178, ...,  0.5022489 ,
         0.51481538, -0.90384686],
       [ 0.45043748,  0.41992001, -1.20778131, ..., -2.04121937,
        -0.47247414,  0.74717906],
       [-0.52015506, -1.24327759, -1.37744919, ..., -0.47851414,
         1.20138627, -1.55268942]])

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
knn = KNeighborsClassifier(n_neighbors=6)

In [22]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [23]:
y_pred = knn.predict(x_test)

In [24]:
y_pred

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [25]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report

In [33]:
print(confusion_matrix(y_pred,y_test))

[[ 81   8]
 [  5 106]]


In [34]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.94      0.91      0.93        89
           1       0.93      0.95      0.94       111

    accuracy                           0.94       200
   macro avg       0.94      0.93      0.93       200
weighted avg       0.94      0.94      0.93       200



In [39]:
error_rate = []
for i in range(1,50):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    pred_i = knn.predict(x_test)
    error_rate.append(np.mean(pred_i != y_test))

In [41]:
error_rate

[0.12,
 0.13,
 0.095,
 0.095,
 0.07,
 0.065,
 0.07,
 0.08,
 0.07,
 0.06,
 0.065,
 0.065,
 0.07,
 0.075,
 0.075,
 0.075,
 0.075,
 0.075,
 0.075,
 0.075,
 0.07,
 0.07,
 0.065,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.065,
 0.07,
 0.07,
 0.075,
 0.075,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.07,
 0.075,
 0.065,
 0.07,
 0.065,
 0.06,
 0.06,
 0.06]

In [42]:
len(error_rate)

49

In [ ]:
plt.figure(figsize=(10,7))
plt.plot(range(1,50),error_rate,color='blue',ls='dashed',marker='*',markerfacecolor ='red')
plt.title('Error rate and k-value')
plt.xlabel('k_v