In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [11]:
iris = pd.read_csv('iris.csv',names=['sep_l','sepl_w','petal_l','petal_w','label'])

In [12]:
iris

sep_l  sepl_w  petal_l  petal_w           label
0      5.1     3.5      1.4      0.2     Iris-setosa
1      4.9     3.0      1.4      0.2     Iris-setosa
2      4.7     3.2      1.3      0.2     Iris-setosa
3      4.6     3.1      1.5      0.2     Iris-setosa
4      5.0     3.6      1.4      0.2     Iris-setosa
..     ...     ...      ...      ...             ...
145    6.7     3.0      5.2      2.3  Iris-virginica
146    6.3     2.5      5.0      1.9  Iris-virginica
147    6.5     3.0      5.2      2.0  Iris-virginica
148    6.2     3.4      5.4      2.3  Iris-virginica
149    5.9     3.0      5.1      1.8  Iris-virginica

[150 rows x 5 columns]

# Encoding categorical variables

# #label encode

In [14]:
#Label encoding is a process of assigning numerical labels to categorical data values. 
#It is a simple and efficient way to convert categorical data into numerical data that can be used for analysis and modelling.

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [20]:
iris['label']=le.fit_transform(iris['label'])     #labels are convertet as setosa=0,versicolor=1,verginica=2

In [22]:
y_test = iris.iloc[:,4].values             #clierly visible

In [23]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

# One hot encoder

In [24]:
iris = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [25]:
iris

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
ohe = OneHotEncoder()

In [43]:
y = iris.iloc[:,4].values

In [44]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [45]:
y = y.reshape(-1,1)

In [46]:
y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [47]:
ohe.fit_transform(y).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [48]:
iris

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
le = LabelEncoder()

In [51]:
iris['label']=le.fit_transform(iris['label'])

In [52]:
iris

sep_l  sep_w  pet_l  pet_w  label
0      5.1    3.5    1.4    0.2      0
1      4.9    3.0    1.4    0.2      0
2      4.7    3.2    1.3    0.2      0
3      4.6    3.1    1.5    0.2      0
4      5.0    3.6    1.4    0.2      0
..     ...    ...    ...    ...    ...
145    6.7    3.0    5.2    2.3      2
146    6.3    2.5    5.0    1.9      2
147    6.5    3.0    5.2    2.0      2
148    6.2    3.4    5.4    2.3      2
149    5.9    3.0    5.1    1.8      2

[150 rows x 5 columns]

In [53]:
x = iris.iloc[:,0:4].values

In [54]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [55]:
y = iris.iloc[:,4].values

In [56]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [60]:
x_train.shape

(120, 4)

In [61]:
x_test.shape

(30, 4)

# StandardScalar

In [62]:
#it will transform your data such that its distribution will have a mean value 0 and standard deviation of 1.

In [64]:
from sklearn.preprocessing import StandardScaler

In [66]:
sc = StandardScaler()

In [67]:
x_train = sc.fit_transform(x_train)

In [68]:
x_train

array([[ 0.31553662, -0.03612186,  0.44748582,  0.2345312 ],
       [ 2.2449325 , -0.03612186,  1.29803965,  1.39642889],
       [-0.2873996 , -1.240184  ,  0.0505607 , -0.15276803],
       [ 0.67729835, -0.51774672,  1.01452171,  1.13822941],
       [-0.04622511, -0.51774672,  0.73100376,  1.52552864],
       [-0.64916132,  1.64956512, -1.31032543, -1.31466572],
       [-0.40798684, -1.72180885,  0.10726429,  0.10543146],
       [-0.76974857,  0.92712784, -1.36702901, -1.31466572],
       [ 0.79788559, -0.51774672,  0.44748582,  0.36363094],
       [ 1.03906007, -1.240184  ,  1.12792888,  0.75093018],
       [ 1.15964732, -0.03612186,  0.95781812,  1.13822941],
       [-0.89033581,  1.16794027, -1.36702901, -1.18556598],
       [ 0.19494938, -1.96262128,  0.67430017,  0.36363094],
       [ 0.5567111 , -0.27693429,  1.01452171,  0.75093018],
       [ 0.91847283, -0.27693429,  0.44748582,  0.10543146],
       [ 2.2449325 , -0.99937157,  1.75166836,  1.39642889],
       [-0.16681235,  1.

In [69]:
x_test = sc.transform(x_test)

In [70]:
x_test

array([[-0.04622511,  2.3720024 , -1.48043619, -1.31466572],
       [-0.89033581, -1.240184  , -0.4597716 , -0.15276803],
       [ 0.91847283, -0.03612186,  0.33407864,  0.2345312 ],
       [-0.52857408,  2.13118998, -1.4237326 , -1.05646624],
       [ 2.48610699,  1.89037755,  1.46815041,  1.00912966],
       [ 0.5567111 ,  0.68631542,  0.50418941,  0.49273069],
       [ 1.28023456,  0.20469056,  0.73100376,  1.39642889],
       [-0.89033581,  1.89037755, -1.08351107, -1.05646624],
       [-1.37268478,  0.44550299, -1.25362184, -1.31466572],
       [ 1.28023456,  0.44550299,  1.07122529,  1.39642889],
       [-0.2873996 , -0.75855914,  0.22067147,  0.10543146],
       [-0.52857408,  2.13118998, -1.19691825, -1.05646624],
       [ 1.52140905, -0.03612186,  1.18463247,  1.13822941],
       [ 0.67729835,  0.44550299,  0.39078223,  0.36363094],
       [ 0.19494938, -0.27693429,  0.39078223,  0.36363094],
       [-1.73444651,  0.44550299, -1.4237326 , -1.31466572],
       [-0.04622511, -0.

# MinMaxScaler

In [71]:
#subtracts the minimum value from each data point and then divides the result by the difference between the maximum and minimum values.
#This results in a dataset with values

In [73]:
x = iris.iloc[:,0:4].values
y = iris.iloc[:,4].values
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [74]:
x_train.shape

(120, 4)

In [75]:
x_test.shape

(30, 4)

In [76]:
x_train

array([[6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2

In [78]:
from sklearn.preprocessing import MinMaxScaler

In [82]:
min_max_scaler = MinMaxScaler(feature_range=(0,1))

In [83]:
x_train_min_max = min_max_scaler.fit_transform(x_train)

In [84]:
x_train_min_max

array([[0.58333333, 0.45833333, 0.75862069, 0.70833333],
       [0.30555556, 0.41666667, 0.5862069 , 0.58333333],
       [0.25      , 0.625     , 0.06896552, 0.04166667],
       [0.5       , 0.41666667, 0.65517241, 0.70833333],
       [0.58333333, 0.33333333, 0.77586207, 0.875     ],
       [0.25      , 0.29166667, 0.48275862, 0.54166667],
       [0.38888889, 0.75      , 0.10344828, 0.08333333],
       [0.47222222, 0.29166667, 0.68965517, 0.625     ],
       [0.44444444, 0.41666667, 0.53448276, 0.58333333],
       [0.41666667, 0.25      , 0.5       , 0.45833333],
       [0.69444444, 0.41666667, 0.75862069, 0.83333333],
       [0.11111111, 0.5       , 0.03448276, 0.04166667],
       [0.72222222, 0.45833333, 0.68965517, 0.91666667],
       [0.19444444, 0.625     , 0.0862069 , 0.20833333],
       [0.30555556, 0.70833333, 0.06896552, 0.04166667],
       [0.19444444, 0.        , 0.4137931 , 0.375     ],
       [0.61111111, 0.41666667, 0.75862069, 0.70833333],
       [0.66666667, 0.54166667,

In [85]:
x_test_min_max = min_max_scaler.transform(x_test)

In [86]:
x_test_min_max

array([[ 0.41666667,  0.33333333,  0.68965517,  0.95833333],
       [ 0.47222222,  0.08333333,  0.5       ,  0.375     ],
       [ 0.33333333,  0.91666667,  0.05172414,  0.04166667],
       [ 0.83333333,  0.375     ,  0.89655172,  0.70833333],
       [ 0.19444444,  0.58333333,  0.06896552,  0.04166667],
       [ 0.55555556,  0.54166667,  0.84482759,  1.        ],
       [ 0.19444444,  0.625     ,  0.03448276,  0.08333333],
       [ 0.66666667,  0.45833333,  0.62068966,  0.58333333],
       [ 0.69444444,  0.33333333,  0.63793103,  0.54166667],
       [ 0.5       ,  0.33333333,  0.5       ,  0.5       ],
       [ 0.5       ,  0.25      ,  0.77586207,  0.54166667],
       [ 0.58333333,  0.5       ,  0.5862069 ,  0.58333333],
       [ 0.5       ,  0.33333333,  0.62068966,  0.45833333],
       [ 0.61111111,  0.33333333,  0.60344828,  0.58333333],
       [ 0.5       ,  0.375     ,  0.62068966,  0.54166667],
       [ 0.16666667,  0.45833333,  0.06896552,  0.        ],
       [ 0.47222222,  0.

# MaAbsScaler

In [89]:
from sklearn.preprocessing import MaxAbsScaler

In [93]:
max_abs_scaler =MaxAbsScaler()

In [95]:
x_train_max_abs = max_abs_scaler.fit_transform (x_train)

In [96]:
x_train_max_abs

array([[0.81012658, 0.70454545, 0.79710145, 0.72      ],
       [0.6835443 , 0.68181818, 0.65217391, 0.6       ],
       [0.65822785, 0.79545455, 0.2173913 , 0.08      ],
       [0.7721519 , 0.68181818, 0.71014493, 0.72      ],
       [0.81012658, 0.63636364, 0.8115942 , 0.88      ],
       [0.65822785, 0.61363636, 0.56521739, 0.56      ],
       [0.72151899, 0.86363636, 0.24637681, 0.12      ],
       [0.75949367, 0.61363636, 0.73913043, 0.64      ],
       [0.74683544, 0.68181818, 0.60869565, 0.6       ],
       [0.73417722, 0.59090909, 0.57971014, 0.48      ],
       [0.86075949, 0.68181818, 0.79710145, 0.84      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.87341772, 0.70454545, 0.73913043, 0.92      ],
       [0.63291139, 0.79545455, 0.23188406, 0.24      ],
       [0.6835443 , 0.84090909, 0.2173913 , 0.08      ],
       [0.63291139, 0.45454545, 0.50724638, 0.4       ],
       [0.82278481, 0.68181818, 0.79710145, 0.72      ],
       [0.84810127, 0.75      ,

In [97]:
x_test_max_abs = max_abs_scaler.transform(x_test)

In [98]:
x_test_max_abs

array([[0.73417722, 0.63636364, 0.73913043, 0.96      ],
       [0.75949367, 0.5       , 0.57971014, 0.4       ],
       [0.69620253, 0.95454545, 0.20289855, 0.08      ],
       [0.92405063, 0.65909091, 0.91304348, 0.72      ],
       [0.63291139, 0.77272727, 0.2173913 , 0.08      ],
       [0.79746835, 0.75      , 0.86956522, 1.        ],
       [0.63291139, 0.79545455, 0.1884058 , 0.12      ],
       [0.84810127, 0.70454545, 0.68115942, 0.6       ],
       [0.86075949, 0.63636364, 0.69565217, 0.56      ],
       [0.7721519 , 0.63636364, 0.57971014, 0.52      ],
       [0.7721519 , 0.59090909, 0.8115942 , 0.56      ],
       [0.81012658, 0.72727273, 0.65217391, 0.6       ],
       [0.7721519 , 0.63636364, 0.68115942, 0.48      ],
       [0.82278481, 0.63636364, 0.66666667, 0.6       ],
       [0.7721519 , 0.65909091, 0.68115942, 0.56      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.04      ],
       [0.75949367, 0.65909091, 0.65217391, 0.6       ],
       [0.69620253, 0.59090909,

# Imputing Missing Values

In [99]:
test = np.array([[2,2],[3,4],[4,5],[np.nan,np.nan]])

In [100]:
test

array([[ 2.,  2.],
       [ 3.,  4.],
       [ 4.,  5.],
       [nan, nan]])

In [101]:
from sklearn.impute import SimpleImputer

In [102]:
imp = SimpleImputer(missing_values=np.nan,strategy='mean')

In [105]:
test_1 = imp.fit_transform(test)

In [106]:
test_1

array([[2.        , 2.        ],
       [3.        , 4.        ],
       [4.        , 5.        ],
       [3.        , 3.66666667]])